### ISSUE TITLE
AmazonEC2; Status Code: 400; Error Code: InvalidParameterValue

### ISSUE THREAD

**Issue by mr-tanta** [ZoccoCss/kalisoc#1]
Value (KaliPurpleSSMFullAccess) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 8c072f47-40cf-405b-842f-6298208c9ec4; Proxy: null)
 
 
<img width="1717" alt="Screenshot 2023-11-11 at 1 58 53 PM" src="https://github.com/ZoccoCss/kalisoc/assets/80099226/24d7faf8-163b-4cf4-aa8d-37dc6db8c479">

**Comment by ZoccoCss** [comment]
You need to create an IAM role named `KaliPurpleSSMFullAccess` in order to launch the stack. This is also true for `KaliPurpleGuacamole` in case you want to use the Guacamole Bastion.

**Comment by ZoccoCss** [comment]
Edited the Readme .txt file
